services:
  vulguard-gpu:
    container_name: vulguard-gpu
    image: vulguard-gpu:latest
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: bash

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
